# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CodacManager', '0003_auto_20160120_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('groupname', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='HostGroupRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodacManager.Groups')),
            ],
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=64, null=True)),
                ('user', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='WorkDir',
            fields=[
                ('taskname', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('director', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='mailaddr',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='hostgrouprelation',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodacManager.Hosts'),
        ),
    ]
