# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodacManager', '0004_auto_20160121_1155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='Hosts',
            new_name='Host',
        ),
    ]
