# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodacManager', '0006_ioc'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('group', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('host', models.ManyToManyField(to='CodacManager.Host')),
            ],
        ),
    ]
