# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodacManager', '0007_hostgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostgrouprelation',
            name='group',
        ),
        migrations.RemoveField(
            model_name='hostgrouprelation',
            name='host',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='HostGroupRelation',
        ),
    ]
